### ISSUE TITLE
Слишком жесткий анализатор

### ISSUE THREAD

**Issue by mozerrr** [smmarty/github_actions_flutter#1]
Сейчас анализатор падает при "warning" и "info".
https://github.com/smmarty/github_actions_flutter/blob/5c50619a06190cf1ff4ae0dcef4b119a322604a0/actions/check/action.yml#L8
Мне кажется это сильно ограничивает использование анализатора. Я думаю стоит сделать данные параметры опциональными. Допустим чтоб при релизе учитывались все, а при деве ток "error".

**Comment by sna2021** [comment]
удалено --fatal-infos

**Comment by mozerrr** [comment]
<img width="1296" alt="изображение" src="https://user-images.githubusercontent.com/24671272/203747260-e3fc8185-fcf3-4c21-b530-0d6a425ea425.png">
Фикс не работает
